### ISSUE TITLE
Transaction loading spinner has faulty React CSS properties

### ISSUE THREAD

**Issue by Martynas-S** [moneybunney/MoneyBunney#26]
![2019-04-24-115242_914x961_scrot](https://user-images.githubusercontent.com/10373535/56646082-8507a680-6687-11e9-86b6-786cf5659d17.png)

**Comment by Andrius-B** [comment]
Nice

**Comment by Martynas-S** [comment]
Supranti, viskas veikia, tik react complainina del pavadinimu ;D
