### ISSUE TITLE
On creating transaction it alerts instead of doing something meaningful

### ISSUE THREAD

**Issue by Martynas-S** [moneybunney/MoneyBunney#28]
![2019-04-24-120503_793x845_scrot](https://user-images.githubusercontent.com/10373535/56647104-8b971d80-6689-11e9-9be0-7af09b3eef65.png)

**Comment by MantasGra** [comment]
There is another problem here, it alerts "success" even when response status is not 201. I found this by working on adding user association to transaction. In that case even if I forcefully remove the 'Token' cookie and get response status 401 it still alerts success.
