### ISSUE TITLE
A default account should be created on user registration

### ISSUE THREAD

**Issue by Andrius-B** [moneybunney/MoneyBunney#64]
Requiring users to use a valid account to create a new transaction, without saying it explicitly is bad UX. We should either add a step to the registration process for creating an account or just create a default account (say `Cash`) in the background

**Comment by Martynas-S** [comment]
> Registra**c**tion

**Comment by Andrius-B** [comment]
> > Registra**c**tion

Whoopsy

**Comment by Martynas-S** [comment]
Agree, probably should create a default account for the user. `Cash` sounds alright

**Comment by MantasGra** [comment]
Closed via #77
