### ISSUE TITLE
Transaction list doesn't display long descriptions correctly

### ISSUE THREAD

**Issue by MantasGra** [moneybunney/MoneyBunney#80]
When provided a long description, transaction list item has text overlapping expense/income amount as shown here:
![image](https://user-images.githubusercontent.com/47576481/58387285-f59e3c00-8014-11e9-9ca8-08923938fdd9.png)

**Comment by Martynas-S** [comment]
@Andrius-B can you check this out?

**Comment by Andrius-B** [comment]
I'll check it out this evening
